-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.achievements
(
    id serial NOT NULL,
    user_id integer,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    competition_name character varying(255) COLLATE pg_catalog."default",
    competition_date date,
    competition_level character varying(50) COLLATE pg_catalog."default",
    competition_place character varying(100) COLLATE pg_catalog."default",
    category character varying(100) COLLATE pg_catalog."default",
    file_path character varying(500) COLLATE pg_catalog."default",
    file_name character varying(255) COLLATE pg_catalog."default",
    file_type character varying(100) COLLATE pg_catalog."default",
    file_size bigint,
    project_file_path character varying(500) COLLATE pg_catalog."default",
    project_file_name character varying(255) COLLATE pg_catalog."default",
    project_file_type character varying(100) COLLATE pg_catalog."default",
    project_file_size bigint,
    teacher_confirmed boolean DEFAULT false,
    confirmed_by integer,
    confirmed_at timestamp without time zone,
    teacher_comment text COLLATE pg_catalog."default",
    teacher_recommendation text COLLATE pg_catalog."default",
    teacher_signature text COLLATE pg_catalog."default",
    qr_token character varying(100) COLLATE pg_catalog."default",
    is_public boolean DEFAULT true,
    share_token character varying(100) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT achievements_pkey PRIMARY KEY (id),
    CONSTRAINT achievements_qr_token_key UNIQUE (qr_token),
    CONSTRAINT achievements_share_token_key UNIQUE (share_token)
);

CREATE TABLE IF NOT EXISTS public.achievex_achievements
(
    id serial NOT NULL,
    user_id integer,
    title character varying(500) COLLATE pg_catalog."default" NOT NULL,
    competition_name character varying(500) COLLATE pg_catalog."default",
    competition_date date,
    level character varying(100) COLLATE pg_catalog."default",
    place character varying(100) COLLATE pg_catalog."default",
    category character varying(100) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    file_path character varying(500) COLLATE pg_catalog."default",
    file_name character varying(500) COLLATE pg_catalog."default",
    file_type character varying(100) COLLATE pg_catalog."default",
    file_size bigint,
    project_file_path character varying(500) COLLATE pg_catalog."default",
    project_file_name character varying(500) COLLATE pg_catalog."default",
    project_file_type character varying(100) COLLATE pg_catalog."default",
    project_file_size bigint,
    verified boolean DEFAULT false,
    verified_by integer,
    verified_at timestamp without time zone,
    teacher_comment text COLLATE pg_catalog."default",
    teacher_recommendation text COLLATE pg_catalog."default",
    digital_signature text COLLATE pg_catalog."default",
    qr_code_token character varying(255) COLLATE pg_catalog."default",
    is_public boolean DEFAULT true,
    share_token character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT achievex_achievements_pkey PRIMARY KEY (id),
    CONSTRAINT achievex_achievements_qr_code_token_key UNIQUE (qr_code_token),
    CONSTRAINT achievex_achievements_share_token_key UNIQUE (share_token)
);

CREATE TABLE IF NOT EXISTS public.chat_members
(
    id serial NOT NULL,
    chat_id integer,
    user_id integer,
    joined_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chat_members_pkey PRIMARY KEY (id),
    CONSTRAINT chat_members_chat_id_user_id_key UNIQUE (chat_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.chat_messages
(
    id serial NOT NULL,
    chat_id integer,
    user_id integer NOT NULL,
    user_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chat_messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.chat_read_status
(
    chat_id integer NOT NULL,
    user_id integer NOT NULL,
    last_read_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chat_read_status_pkey PRIMARY KEY (chat_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.chats
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_by integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chats_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.competition_documents
(
    id serial NOT NULL,
    competition_id integer NOT NULL,
    user_id integer NOT NULL,
    file_name character varying(500) COLLATE pg_catalog."default" NOT NULL,
    original_name character varying(500) COLLATE pg_catalog."default" NOT NULL,
    file_path character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    file_size integer NOT NULL,
    file_type character varying(100) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    uploaded_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT competition_documents_pkey PRIMARY KEY (id),
    CONSTRAINT competition_documents_competition_id_user_id_file_name_key UNIQUE (competition_id, user_id, file_name)
);

COMMENT ON TABLE public.competition_documents
    IS 'Таблиця для зберігання файлів, які учні завантажують до конкурсів';

COMMENT ON COLUMN public.competition_documents.competition_id
    IS 'ID конкурсу';

COMMENT ON COLUMN public.competition_documents.user_id
    IS 'ID учня, який завантажив файл';

COMMENT ON COLUMN public.competition_documents.file_name
    IS 'Унікальне ім''я файлу в системі';

COMMENT ON COLUMN public.competition_documents.original_name
    IS 'Оригінальна назва файлу';

COMMENT ON COLUMN public.competition_documents.file_path
    IS 'Шлях до файлу на сервері';

COMMENT ON COLUMN public.competition_documents.file_size
    IS 'Розмір файлу в байтах';

COMMENT ON COLUMN public.competition_documents.file_type
    IS 'MIME тип файлу';

COMMENT ON COLUMN public.competition_documents.description
    IS 'Опис або коментар до файлу від учня';

CREATE TABLE IF NOT EXISTS public.competition_form_responses
(
    id serial NOT NULL,
    competition_id integer,
    user_id integer,
    form_data jsonb NOT NULL,
    submitted_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT competition_form_responses_pkey PRIMARY KEY (id),
    CONSTRAINT competition_form_responses_competition_id_user_id_key UNIQUE (competition_id, user_id)
);

COMMENT ON TABLE public.competition_form_responses
    IS 'Відповіді учнів на кастомні форми конкурсів';

COMMENT ON COLUMN public.competition_form_responses.form_data
    IS 'JSON об''єкт з відповідями учня на форму';

CREATE TABLE IF NOT EXISTS public.competition_participants
(
    id serial NOT NULL,
    competition_id integer,
    user_id integer,
    added_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    team_id integer,
    telegram_added_notified boolean DEFAULT false,
    CONSTRAINT competition_participants_pkey PRIMARY KEY (id),
    CONSTRAINT competition_participants_competition_id_user_id_key UNIQUE (competition_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.competition_preparations
(
    id serial NOT NULL,
    competition_id integer,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    questions_count integer DEFAULT 0,
    created_by integer,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT competition_preparations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.competition_results
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    competition_id integer NOT NULL,
    score numeric(5, 2) NOT NULL,
    place character varying(10) COLLATE pg_catalog."default" NOT NULL,
    achievement text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    notes text COLLATE pg_catalog."default",
    added_by integer,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    added_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_confirmed boolean DEFAULT false,
    telegram_result_notified boolean DEFAULT false,
    CONSTRAINT competition_results_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.competition_teams
(
    id serial NOT NULL,
    competition_id integer,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_by integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT competition_teams_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.competitions
(
    id serial NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    start_date date NOT NULL,
    end_date date NOT NULL,
    created_by integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    manual_status character varying(20) COLLATE pg_catalog."default",
    subject_id integer,
    level character varying(100) COLLATE pg_catalog."default",
    organizer character varying(255) COLLATE pg_catalog."default",
    location character varying(255) COLLATE pg_catalog."default",
    max_participants integer,
    registration_deadline date,
    requirements text COLLATE pg_catalog."default",
    prizes text COLLATE pg_catalog."default",
    contact_info text COLLATE pg_catalog."default",
    website_url character varying(500) COLLATE pg_catalog."default",
    is_online boolean DEFAULT false,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    custom_fields text COLLATE pg_catalog."default",
    is_team boolean DEFAULT false,
    standard_fields jsonb,
    telegram_new_notified boolean DEFAULT false,
    telegram_deadline_reminder_sent boolean DEFAULT false,
    CONSTRAINT competitions_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.competitions.custom_fields
    IS 'JSON масив з полями форми конкурсу';

CREATE TABLE IF NOT EXISTS public.mentor_favorites
(
    id serial NOT NULL,
    student_id integer NOT NULL,
    teacher_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT mentor_favorites_pkey PRIMARY KEY (id),
    CONSTRAINT mentor_favorites_student_id_mentor_id_key UNIQUE (student_id, teacher_id)
);

CREATE TABLE IF NOT EXISTS public.mentor_materials
(
    id serial NOT NULL,
    teacher_id integer NOT NULL,
    student_id integer,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    material_type character varying(50) COLLATE pg_catalog."default" DEFAULT 'recommendation'::character varying,
    url text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT mentor_materials_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.mentor_requests
(
    id serial NOT NULL,
    student_id integer NOT NULL,
    teacher_id integer NOT NULL,
    subject character varying(255) COLLATE pg_catalog."default",
    message text COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT mentor_requests_pkey PRIMARY KEY (id),
    CONSTRAINT mentor_requests_student_id_mentor_id_key UNIQUE (student_id, teacher_id)
);

CREATE TABLE IF NOT EXISTS public.mentor_schedule
(
    id serial NOT NULL,
    teacher_id integer NOT NULL,
    day_of_week integer NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    is_available boolean DEFAULT true,
    note text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT mentor_schedule_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.news
(
    id serial NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    category character varying(100) COLLATE pg_catalog."default",
    is_published boolean DEFAULT false,
    image_url character varying(255) COLLATE pg_catalog."default",
    author_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    views_count integer DEFAULT 0,
    cover_image_url text COLLATE pg_catalog."default",
    gallery_images text[] COLLATE pg_catalog."default" DEFAULT '{}'::text[],
    is_archived boolean DEFAULT false,
    archived_at timestamp without time zone,
    cover_image character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT news_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.news
    IS 'Таблиця новин платформи';

COMMENT ON COLUMN public.news.views_count
    IS 'Кількість переглядів новини';

CREATE TABLE IF NOT EXISTS public.news_comments
(
    id serial NOT NULL,
    news_id integer NOT NULL,
    user_id integer NOT NULL,
    comment text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT news_comments_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.news_comments
    IS 'Коментарі до новин';

CREATE TABLE IF NOT EXISTS public.news_likes
(
    id serial NOT NULL,
    news_id integer NOT NULL,
    user_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT news_likes_pkey PRIMARY KEY (id),
    CONSTRAINT news_likes_news_id_user_id_key UNIQUE (news_id, user_id)
);

COMMENT ON TABLE public.news_likes
    IS 'Лайки новин';

CREATE TABLE IF NOT EXISTS public.notifications
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    related_id integer,
    related_type character varying(50) COLLATE pg_catalog."default",
    is_read boolean DEFAULT false,
    action_url character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    read_at timestamp without time zone,
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.profiles
(
    id serial NOT NULL,
    user_id integer,
    first_name character varying(100) COLLATE pg_catalog."default",
    last_name character varying(100) COLLATE pg_catalog."default",
    middle_name character varying(100) COLLATE pg_catalog."default",
    telegram character varying(100) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    birth_date date,
    city character varying(100) COLLATE pg_catalog."default",
    school character varying(255) COLLATE pg_catalog."default",
    grade character varying(50) COLLATE pg_catalog."default",
    interests text COLLATE pg_catalog."default",
    bio text COLLATE pg_catalog."default",
    avatar text COLLATE pg_catalog."default",
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    school_id integer,
    grade_number character varying(10) COLLATE pg_catalog."default",
    grade_letter character varying(5) COLLATE pg_catalog."default",
    club_institution character varying(255) COLLATE pg_catalog."default",
    club_name character varying(255) COLLATE pg_catalog."default",
    office_phone character varying(20) COLLATE pg_catalog."default",
    "position" character varying(100) COLLATE pg_catalog."default",
    visible_subject_id integer,
    room_number character varying(50) COLLATE pg_catalog."default",
    experience_years integer DEFAULT 0,
    education text COLLATE pg_catalog."default",
    qualifications text COLLATE pg_catalog."default",
    schedule text COLLATE pg_catalog."default",
    subjects_ids text COLLATE pg_catalog."default",
    grades_catering text COLLATE pg_catalog."default",
    specialization character varying(255) COLLATE pg_catalog."default",
    awards text COLLATE pg_catalog."default",
    methodist_area text COLLATE pg_catalog."default",
    consultation_areas text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    average_score numeric(5, 2),
    teacher_id integer,
    CONSTRAINT profiles_pkey PRIMARY KEY (id),
    CONSTRAINT profiles_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.recommendation_letters
(
    id serial NOT NULL,
    student_id integer NOT NULL,
    teacher_id integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    purpose character varying(255) COLLATE pg_catalog."default",
    student_class character varying(50) COLLATE pg_catalog."default",
    student_school character varying(255) COLLATE pg_catalog."default",
    student_direction character varying(255) COLLATE pg_catalog."default",
    recommendation_text text COLLATE pg_catalog."default" NOT NULL,
    strengths text COLLATE pg_catalog."default",
    achievements text COLLATE pg_catalog."default",
    conclusion text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'draft'::character varying,
    qr_code text COLLATE pg_catalog."default",
    in_portfolio boolean DEFAULT false,
    portfolio_added_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    confirmed_at timestamp without time zone,
    published_at timestamp without time zone,
    CONSTRAINT recommendation_letters_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.rehearsals
(
    id serial NOT NULL,
    competition_id integer NOT NULL,
    teacher_id integer NOT NULL,
    student_id integer,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    rehearsal_date timestamp without time zone NOT NULL,
    location character varying(255) COLLATE pg_catalog."default",
    duration integer,
    is_online boolean DEFAULT false,
    notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rehearsals_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.rehearsals
    IS 'Репетиції конкурсів';

COMMENT ON COLUMN public.rehearsals.student_id
    IS 'Якщо NULL - репетиція для всіх учасників конкурсу, інакше - особиста';

CREATE TABLE IF NOT EXISTS public.schools
(
    id integer NOT NULL,
    name character varying(500) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT schools_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.subjects
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    category character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT subjects_pkey PRIMARY KEY (id),
    CONSTRAINT subjects_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.sync_history
(
    id serial NOT NULL,
    sync_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    sync_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_count integer DEFAULT 0,
    updated_count integer DEFAULT 0,
    deleted_count integer DEFAULT 0,
    total_count integer DEFAULT 0,
    has_errors boolean DEFAULT false,
    error_message text COLLATE pg_catalog."default",
    details jsonb,
    duration_ms integer,
    initiated_by integer,
    CONSTRAINT sync_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.teacher_competition_subscriptions
(
    id serial NOT NULL,
    teacher_id integer,
    competition_id integer,
    subscribed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT teacher_competition_subscriptions_pkey PRIMARY KEY (id),
    CONSTRAINT teacher_competition_subscriptions_teacher_id_competition_id_key UNIQUE (teacher_id, competition_id)
);

CREATE TABLE IF NOT EXISTS public.telegram_subscriptions
(
    id serial NOT NULL,
    user_id integer,
    chat_id bigint NOT NULL,
    username character varying(255) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    subscribed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT telegram_subscriptions_pkey PRIMARY KEY (id),
    CONSTRAINT telegram_subscriptions_chat_id_key UNIQUE (chat_id),
    CONSTRAINT telegram_subscriptions_user_id_chat_id_key UNIQUE (user_id, chat_id)
);

CREATE TABLE IF NOT EXISTS public.testimonials
(
    id serial NOT NULL,
    user_id integer,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(100) COLLATE pg_catalog."default" NOT NULL,
    rating integer NOT NULL,
    text text COLLATE pg_catalog."default" NOT NULL,
    is_approved boolean DEFAULT false,
    is_featured boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT testimonials_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default",
    role user_role DEFAULT 'учень'::user_role,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    telegram_chat_id bigint,
    google_id character varying(255) COLLATE pg_catalog."default",
    display_name character varying(255) COLLATE pg_catalog."default",
    is_blocked boolean DEFAULT false,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_google_id_key UNIQUE (google_id),
    CONSTRAINT users_telegram_chat_id_key UNIQUE (telegram_chat_id)
);

ALTER TABLE IF EXISTS public.achievements
    ADD CONSTRAINT achievements_confirmed_by_fkey FOREIGN KEY (confirmed_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.achievements
    ADD CONSTRAINT achievements_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.achievex_achievements
    ADD CONSTRAINT achievex_achievements_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.achievex_achievements
    ADD CONSTRAINT achievex_achievements_verified_by_fkey FOREIGN KEY (verified_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.chat_members
    ADD CONSTRAINT chat_members_chat_id_fkey FOREIGN KEY (chat_id)
    REFERENCES public.chats (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_chat_members_chat_id
    ON public.chat_members(chat_id);


ALTER TABLE IF EXISTS public.chat_members
    ADD CONSTRAINT chat_members_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_chat_members_user_id
    ON public.chat_members(user_id);


ALTER TABLE IF EXISTS public.chat_messages
    ADD CONSTRAINT chat_messages_chat_id_fkey FOREIGN KEY (chat_id)
    REFERENCES public.chats (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_chat_messages_chat_id
    ON public.chat_messages(chat_id);


ALTER TABLE IF EXISTS public.chat_read_status
    ADD CONSTRAINT chat_read_status_chat_id_fkey FOREIGN KEY (chat_id)
    REFERENCES public.chats (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.chat_read_status
    ADD CONSTRAINT chat_read_status_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.chats
    ADD CONSTRAINT chats_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.competition_documents
    ADD CONSTRAINT competition_documents_competition_id_fkey FOREIGN KEY (competition_id)
    REFERENCES public.competitions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_competition_documents_competition
    ON public.competition_documents(competition_id);


ALTER TABLE IF EXISTS public.competition_documents
    ADD CONSTRAINT competition_documents_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_competition_documents_user
    ON public.competition_documents(user_id);


ALTER TABLE IF EXISTS public.competition_form_responses
    ADD CONSTRAINT competition_form_responses_competition_id_fkey FOREIGN KEY (competition_id)
    REFERENCES public.competitions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_form_responses_competition
    ON public.competition_form_responses(competition_id);


ALTER TABLE IF EXISTS public.competition_form_responses
    ADD CONSTRAINT competition_form_responses_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_form_responses_user
    ON public.competition_form_responses(user_id);


ALTER TABLE IF EXISTS public.competition_participants
    ADD CONSTRAINT competition_participants_competition_id_fkey FOREIGN KEY (competition_id)
    REFERENCES public.competitions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.competition_participants
    ADD CONSTRAINT competition_participants_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.competition_preparations
    ADD CONSTRAINT competition_preparations_competition_id_fkey FOREIGN KEY (competition_id)
    REFERENCES public.competitions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.competition_preparations
    ADD CONSTRAINT competition_preparations_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.competition_results
    ADD CONSTRAINT competition_results_added_by_fkey FOREIGN KEY (added_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.competition_results
    ADD CONSTRAINT competition_results_competition_id_fkey FOREIGN KEY (competition_id)
    REFERENCES public.competitions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.competition_results
    ADD CONSTRAINT competition_results_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.competition_teams
    ADD CONSTRAINT competition_teams_competition_id_fkey FOREIGN KEY (competition_id)
    REFERENCES public.competitions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.competition_teams
    ADD CONSTRAINT competition_teams_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.competitions
    ADD CONSTRAINT competitions_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_competitions_created_by
    ON public.competitions(created_by);


ALTER TABLE IF EXISTS public.competitions
    ADD CONSTRAINT competitions_subject_id_fkey FOREIGN KEY (subject_id)
    REFERENCES public.subjects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_competitions_subject
    ON public.competitions(subject_id);


ALTER TABLE IF EXISTS public.mentor_favorites
    ADD CONSTRAINT mentor_favorites_mentor_id_fkey FOREIGN KEY (teacher_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_mentor_favorites_mentor
    ON public.mentor_favorites(teacher_id);


ALTER TABLE IF EXISTS public.mentor_favorites
    ADD CONSTRAINT mentor_favorites_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_mentor_favorites_student
    ON public.mentor_favorites(student_id);


ALTER TABLE IF EXISTS public.mentor_materials
    ADD CONSTRAINT mentor_materials_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_mentor_materials_student
    ON public.mentor_materials(student_id);


ALTER TABLE IF EXISTS public.mentor_materials
    ADD CONSTRAINT mentor_materials_teacher_id_fkey FOREIGN KEY (teacher_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_mentor_materials_teacher
    ON public.mentor_materials(teacher_id);


ALTER TABLE IF EXISTS public.mentor_requests
    ADD CONSTRAINT mentor_requests_mentor_id_fkey FOREIGN KEY (teacher_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_mentor_requests_mentor
    ON public.mentor_requests(teacher_id);


ALTER TABLE IF EXISTS public.mentor_requests
    ADD CONSTRAINT mentor_requests_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_mentor_requests_student
    ON public.mentor_requests(student_id);


ALTER TABLE IF EXISTS public.mentor_schedule
    ADD CONSTRAINT mentor_schedule_teacher_id_fkey FOREIGN KEY (teacher_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_mentor_schedule_teacher
    ON public.mentor_schedule(teacher_id);


ALTER TABLE IF EXISTS public.news
    ADD CONSTRAINT news_author_id_fkey FOREIGN KEY (author_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_news_author
    ON public.news(author_id);


ALTER TABLE IF EXISTS public.news_comments
    ADD CONSTRAINT news_comments_news_id_fkey FOREIGN KEY (news_id)
    REFERENCES public.news (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_news_comments_news
    ON public.news_comments(news_id);


ALTER TABLE IF EXISTS public.news_comments
    ADD CONSTRAINT news_comments_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_news_comments_user
    ON public.news_comments(user_id);


ALTER TABLE IF EXISTS public.news_likes
    ADD CONSTRAINT news_likes_news_id_fkey FOREIGN KEY (news_id)
    REFERENCES public.news (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_news_likes_news
    ON public.news_likes(news_id);


ALTER TABLE IF EXISTS public.news_likes
    ADD CONSTRAINT news_likes_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_news_likes_user
    ON public.news_likes(user_id);


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_notifications_user_id
    ON public.notifications(user_id);


ALTER TABLE IF EXISTS public.profiles
    ADD CONSTRAINT profiles_teacher_id_fkey FOREIGN KEY (teacher_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.profiles
    ADD CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS profiles_user_id_key
    ON public.profiles(user_id);


ALTER TABLE IF EXISTS public.profiles
    ADD CONSTRAINT profiles_visible_subject_id_fkey FOREIGN KEY (visible_subject_id)
    REFERENCES public.subjects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.recommendation_letters
    ADD CONSTRAINT recommendation_letters_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_rec_letters_student
    ON public.recommendation_letters(student_id);


ALTER TABLE IF EXISTS public.recommendation_letters
    ADD CONSTRAINT recommendation_letters_teacher_id_fkey FOREIGN KEY (teacher_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_rec_letters_teacher
    ON public.recommendation_letters(teacher_id);


ALTER TABLE IF EXISTS public.rehearsals
    ADD CONSTRAINT rehearsals_competition_id_fkey FOREIGN KEY (competition_id)
    REFERENCES public.competitions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_rehearsals_competition
    ON public.rehearsals(competition_id);


ALTER TABLE IF EXISTS public.rehearsals
    ADD CONSTRAINT rehearsals_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_rehearsals_student
    ON public.rehearsals(student_id);


ALTER TABLE IF EXISTS public.rehearsals
    ADD CONSTRAINT rehearsals_teacher_id_fkey FOREIGN KEY (teacher_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_rehearsals_teacher
    ON public.rehearsals(teacher_id);


ALTER TABLE IF EXISTS public.sync_history
    ADD CONSTRAINT sync_history_initiated_by_fkey FOREIGN KEY (initiated_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.teacher_competition_subscriptions
    ADD CONSTRAINT teacher_competition_subscriptions_competition_id_fkey FOREIGN KEY (competition_id)
    REFERENCES public.competitions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.teacher_competition_subscriptions
    ADD CONSTRAINT teacher_competition_subscriptions_teacher_id_fkey FOREIGN KEY (teacher_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.telegram_subscriptions
    ADD CONSTRAINT telegram_subscriptions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.testimonials
    ADD CONSTRAINT testimonials_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

END;